### ISSUE TITLE
Transfer of aws marketplace subscription to another account

### ISSUE THREAD

**Issue by nikhilpulluri** [awsdocs/aws-marketplace-user-guide-for-buyers#1]
The scenario is:

1. User 1 has subscribed to a service in aws Marketplace.
2.User 1 dont want to manage it and want to transfer his subscription to another User 2 account.
3. During this transfer, all the unpaid amount also needs to be transfered to the user 2.

Is there any way we can do this in AWS

**Comment by jennifer-yu-21** [comment]
Thank you for your request. I'll add it to the team's list of items for future consideration and then close this issue.
